export const SET_LUNBO_LIST = 'SET_LUNBO_LIST';
export const SET_HOTFICTION_LIST = 'SET_HOTFICTION_LIST';
export const SET_FREEFICTION_LIST = 'SET_FREEFICTION_LIST';
export const SET_NEWFICTION_LIST = 'SET_NEWFICTION_LIST';
export const SET_QINGFICTION_LIST = 'SET_QINGFICTION_LIST';
export const SET_NAVBAR_TITLE = 'SET_NAVBAR_TITLE';
export const SET_SEARCH = 'SET_SEARCH';
export const SET_SEARCHKW = 'SET_SEARCHKW';